<?php
return [
    'group' => [
        ['name'=>'微信','key'=>'wechat'],
        ['name'=>'支付宝','key'=>'alipay'],
        ['name'=>'苹果','key'=>'apple'],
    ],
    'items' => [
        'wechat' => [
            [
                'name'=>'单行输入框1'
                ,'tip'=>'单行输入框1'
                ,'key'=>'input'
                ,'type'=>'input'
                ,'content'=>''
            ],
            [
                'name'=>'普通文本域1'
                ,'tip'=>'普通文本域1'
                ,'key'=>'textarea'
                ,'type'=>'textarea'
                ,'content'=>''
            ],
            [
                'name'=>'状态(开关单选)'
                ,'tip'=>'状态(开关单选)'
                ,'key'=>'status'
                ,'type'=>'radio'
                ,'default'=>2
                ,'content'=>[
                '1'=>'关闭'
                ,'2'=>'打开'
            ]
            ],
            [
                'name'=>'单选下拉框'
                ,'tip'=>'单选下拉框'
                ,'key'=>'hero'
                ,'type'=>'select_single'
                ,'default'=>'4'
                ,'content'=>[
                '1'=>'秀逗魔法师'
                ,'2'=>'受折磨的灵魂'
                ,'3'=>'船长'
                ,'4'=>'虚空假面'
                ,'5'=>'幻影刺客'
                ,'6'=>'谜团'
                ,'7'=>'全能骑士'
                ,'8'=>'敌法师'
            ]
            ],
            [
                'name'=>'多选下拉框'
                ,'tip'=>'多选下拉框'
                ,'key'=>'sign'
                ,'type'=>'select_multi'
                ,'default'=>'1,3'
                ,'content'=>[
                '1'=>'热门'
                ,'2'=>'首页'
                ,'3'=>'顶级分类推荐'
                ,'4'=>'二级分类推荐'
                ,'5'=>'特定分类推荐'
                ,'6'=>'轮播图'
                ,'7'=>'置顶'
                ,'8'=>'新闻'
            ]
            ],
            [
                'name'=>'单图'
                ,'tip'=>'单图'
                ,'key'=>'image'
                ,'type'=>'image_single'
            ],
            [
                'name'=>'多图'
                ,'tip'=>'多图'
                ,'key'=>'images'
                ,'type'=>'image_multi'
            ],
            [
                'name'=>'单视频'
                ,'tip'=>'单视频'
                ,'key'=>'video'
                ,'type'=>'video_single'
            ],
            [
                'name'=>'多视频'
                ,'tip'=>'多视频'
                ,'key'=>'videos'
                ,'type'=>'video_multi'
            ],
            [
                'name'=>'单文件'
                ,'tip'=>'单文件'
                ,'key'=>'file'
                ,'type'=>'file_single'
            ],
            [
                'name'=>'多文件'
                ,'tip'=>'多文件'
                ,'key'=>'files'
                ,'type'=>'file_multi'
            ],
            [
                'name'=>'数组'
                ,'tip'=>'数组'
                ,'key'=>'array'
                ,'type'=>'array'
            ],
            [
                'name'=>'富文本编辑器'
                ,'tip'=>'富文本编辑器'
                ,'key'=>'ueditor'
                ,'type'=>'ueditor'
            ]
        ],
        'alipay' => [
            [
                'name'=>'网关地址'
                ,'tip'=>'单行输入框2'
                ,'key'=>'gatewayUrl'
                ,'type'=>'input'
                ,'content'=>'https://openapi.alipay.com/gateway.do'
            ],
            [
                'name'=>'应用ID'
                ,'tip'=>'支付宝开放平台创建应用得到的ID'
                ,'key'=>'appId'
                ,'type'=>'input'
                ,'content'=>''
            ],
            [
                'name'=>'rsa私钥'
                ,'tip'=>'rsa私钥'
                ,'key'=>'rsaPrivateKey'
                ,'type'=>'input'
                ,'content'=>''
            ],
            [
                'name'=>'rsa公钥'
                ,'tip'=>'rsa公钥'
                ,'key'=>'alipayrsaPublicKey'
                ,'type'=>'input'
                ,'content'=>''
            ],
            [
                'name'=>'签名类型'
                ,'tip'=>'签名类型'
                ,'key'=>'signType'
                ,'type'=>'input'
                ,'content'=>'RSA2'
            ],
            [
                'name'=>'字符集'
                ,'tip'=>'请求接口传递参数使用的字符集'
                ,'key'=>'postCharset'
                ,'type'=>'input'
                ,'content'=>'UTF-8'
            ],
            [
                'name'=>'数据格式'
                ,'tip'=>'数据格式，默认使用json'
                ,'key'=>'format'
                ,'type'=>'input'
                ,'content'=>'json'
            ],
            [
                'name'=>'支付回调通知接口地址'
                ,'tip'=>'支付回调通知接口地址'
                ,'key'=>'notify_url'
                ,'type'=>'input'
                ,'content'=>''
            ],
        ],
        'apple'  => [],
    ],
];