---
## 网站配置
logo:
  ## 网站名称
  title: "Api文档"
  ## 网站图标
  image: "/static/admin/images/logo.png"
## 菜单配置
menu:
  ## 菜单数据来源
  data: "/plugin/apidoc/index/getMenu"
  ## 菜单接口的请求方式 GET / POST
  method: "GET"
  ## 是否同时只打开一个菜单目录
  accordion: true
  ## 是否开启多系统菜单模式
  control: true
  ## 当control为true时，顶部最多显示多少菜单，其他顶部菜单需要点击最后的顶部下拉菜单进行展示
  maxTopMenuNum: 8
  ## 默认选中的菜单项
  select: "1"
  ## 是否开启异步菜单，false 时 data 属性设置为菜单数据，true 时为 json 文件或后端接口
  async: true
## 视图内容配置
tab:
  ## 是否开启多选项卡
  muiltTab: true
  ## 保持视图状态
  keepState: false
  ## 开启选项卡记忆
  session: true
  ## 最大可打开的选项卡数量
  tabMax: "30"
  ## 首页
  index:
    id: "2" ## 标识 ID , 建议与菜单项中的 ID 一致
    href: "/admin/console.html" ## 页面地址
    title: "控制面板" ## 标题
## 主题配置
theme:
  ## 默认主题色，对应 colors 配置中的 ID 标识
  defaultColor: "2"
  ## 默认的菜单主题 dark-theme 黑 / light-theme 白
  defaultMenu: "dark-theme"
  ## 是否允许用户切换主题，false 时关闭自定义主题面板
  allowCustom: true
## 主题色配置列表
colors:
  - id: "1"
    color: "#2d8cf0"
  - id: "2"
    color: "#36b368"
  - id: "3"
    color: "#f6ad55"
  - id: "4"
    color: "#f56c6c"
  - id: "5"
    color: "#3963bc"
## 主题面板的链接列表
links:
  - icon: "layui-icon layui-icon-website"
    title: "官方网站"
    href: "http://www.laytp.com"
  - icon: "layui-icon layui-icon-read"
    title: "开发文档"
    href: "http://www.laytp.com/doc/"
  - icon: "layui-icon layui-icon-fonts-code"
    title: "开源地址"
    href: "https://gitee.com/junstar/laytp"
## 其他配置
other:
  ## 主页动画时长
  keepLoad: "500"
  ## 布局顶部主题
  autoHead: false
## 头部配置
header:
  ## 站内消息，数据来源，通过 false 设置关闭
  message: false