<?php
return [
    [
        'name'=>'上传开关'
        ,'key'=>'open_status'
        ,'type'=>'radio'
        ,'default'=>'close'
        ,'content'=>[
        'close'=>'关闭'
        ,'open'=>'打开'
    ]
    ],
    [
        'name'=>'accessKey'
        ,'key'=>'access_key'
        ,'type'=>'input'
        ,'content'=>''
    ],
    [
        'name'=>'secretKey'
        ,'key'=>'secret_key'
        ,'type'=>'input'
        ,'content'=>''
    ],
    [
        'name'=>'bucket'
        ,'key'=>'bucket'
        ,'type'=>'input'
        ,'content'=>''
    ],
    [
        'name'=>'空间域名'
        ,'key'=>'domain'
        ,'type'=>'input'
        ,'content'=>''
    ],
];
