<?php

use think\migration\Migrator;

class PluginCoreMenu extends Migrator
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function change()
    {
        $table = $this->table('plugin_core_menu', [
            'engine' => 'InnoDB',
            'comment' => '后台菜单',
            'collation' => 'utf8mb4_general_ci'
        ]);

        if ($table->exists()) {
            $table->drop();
        }

        $table
            ->addColumn('name', 'string', ['length' => 100, 'default' => '', 'comment' => '名称'])
            ->addColumn('rule', 'string', ['length' => 100, 'default' => '', 'comment' => '路由规则'])
            ->addColumn('is_menu', 'boolean', ['default' => 1, 'comment' => '是否为menu.2=不是,1=是'])
            ->addColumn('sort', 'integer', ['default' => 0, 'comment' => '排序，从大到小，倒叙排序'])
            ->addColumn('pid', 'integer', ['default' => 0, 'comment' => '上级ID'])
            ->addColumn('is_show', 'integer', ['default' => 1, 'comment' => '是否显示.2=隐藏,1=显示'])
            ->addColumn('icon', 'string', ['length' => 100, 'default' => '', 'comment' => '图标'])
            ->addColumn('des', 'string', ['length' => 100, 'default' => '', 'comment' => '描述'])
            ->addColumn('create_time', 'integer', ['default' => 0, 'comment' => '创建时间'])
            ->addColumn('update_time', 'integer', ['default' => 0, 'comment' => '更新时间'])
            ->addColumn('delete_time', 'integer', ['default' => 0, 'comment' => '删除时间']);

        $data = [
            '1' => [
                'name' => '控制台',
                'rule' => 'plugin/core/dashboard/index',
                'is_menu' => 1,
                'sort' => 0,
                'pid' => 0,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-console',
                'des' => '控制台',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '2' => [
                'name' => '快捷菜单',
                'rule' => 'plugin/core/dashboard/index',
                'is_menu' => 1,
                'sort' => 0,
                'pid' => 1,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-console',
                'des' => '快捷菜单',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '3' => [
                'name' => '首页',
                'rule' => 'plugin/core/dashboard/index',
                'is_menu' => 1,
                'sort' => 0,
                'pid' => 2,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-home',
                'des' => '首页',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '4' => [
                'name' => '权限管理',
                'rule' => 'plugin/core/auth.user/index',
                'is_menu' => 1,
                'sort' => 0,
                'pid' => 1,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-user',
                'des' => '权限管理',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '5' => [
                'name' => '后台管理员',
                'rule' => 'plugin/core/auth.user/index',
                'is_menu' => 1,
                'sort' => 0,
                'pid' => 4,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-friends',
                'des' => '后台管理员',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '6' => [
                'name' => '添加',
                'rule' => 'plugin/core/auth.user/add',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 5,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-add-circle',
                'des' => '添加',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '7' => [
                'name' => '编辑',
                'rule' => 'plugin/core/auth.user/edit',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 5,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-edit',
                'des' => '编辑',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '8' => [
                'name' => '删除',
                'rule' => 'plugin/core/auth.user/del',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 5,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-delete',
                'des' => '删除',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '9' => [
                'name' => '表格编辑',
                'rule' => 'plugin/core/auth.user/tableEdit',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 5,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-slider',
                'des' => '表格编辑',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '10' => [
                'name' => '回收站',
                'rule' => 'plugin/core/auth.user/recycle',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 5,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-slider',
                'des' => '回收站',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '11' => [
                'name' => '还原',
                'rule' => 'plugin/core/auth.user/restore',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 5,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-refresh-3',
                'des' => '还原',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '12' => [
                'name' => '真实删除',
                'rule' => 'plugin/core/auth.user/trueDel',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 5,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-delete',
                'des' => '真实删除',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '13' => [
                'name' => '回收站表格编辑',
                'rule' => 'plugin/core/auth.user/recycleTableEdit',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 5,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-slider',
                'des' => '回收站表格编辑',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '14' => [
                'name' => '角色管理',
                'rule' => 'plugin/core/auth.role/index',
                'is_menu' => 1,
                'sort' => 0,
                'pid' => 4,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-username',
                'des' => '角色管理',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '15' => [
                'name' => '添加',
                'rule' => 'plugin/core/auth.role/add',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 14,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-add-circle',
                'des' => '添加',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '16' => [
                'name' => '编辑',
                'rule' => 'plugin/core/auth.role/edit',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 14,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-edit',
                'des' => '编辑',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '17' => [
                'name' => '删除',
                'rule' => 'plugin/core/auth.role/del',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 14,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-delete',
                'des' => '删除',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '18' => [
                'name' => '回收站',
                'rule' => 'plugin/core/auth.role/recycle',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 14,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-slider',
                'des' => '回收站',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '19' => [
                'name' => '还原',
                'rule' => 'plugin/core/auth.role/restore',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 14,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-refresh-3',
                'des' => '还原',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '20' => [
                'name' => '真实删除',
                'rule' => 'plugin/core/auth.role/trueDel',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 14,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-delete',
                'des' => '真实删除',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '21' => [
                'name' => '菜单管理',
                'rule' => 'plugin/core/auth.menu/index',
                'is_menu' => 1,
                'sort' => 0,
                'pid' => 4,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-menu-fill',
                'des' => '菜单管理',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '22' => [
                'name' => '添加',
                'rule' => 'plugin/core/auth.menu/add',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 21,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-add-circle',
                'des' => '添加',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '23' => [
                'name' => '编辑',
                'rule' => 'plugin/core/auth.menu/edit',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 21,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-edit',
                'des' => '编辑',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '24' => [
                'name' => '删除',
                'rule' => 'plugin/core/auth.menu/del',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 21,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-delete',
                'des' => '删除',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '25' => [
                'name' => '表格编辑',
                'rule' => 'plugin/core/auth.menu/tableEdit',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 21,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-slider',
                'des' => '表格编辑',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '26' => [
                'name' => '回收站',
                'rule' => 'plugin/core/auth.menu/recycle',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 21,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-slider',
                'des' => '回收站',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '27' => [
                'name' => '还原',
                'rule' => 'plugin/core/auth.menu/restore',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 21,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-refresh-3',
                'des' => '还原',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '28' => [
                'name' => '真实删除',
                'rule' => 'plugin/core/auth.menu/trueDel',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 21,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-delete',
                'des' => '真实删除',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '29' => [
                'name' => '回收站表格编辑',
                'rule' => 'plugin/core/auth.menu/recycleTableEdit',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 21,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-slider',
                'des' => '回收站表格编辑',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '30' => [
                'name' => '常规管理',
                'rule' => 'plugin/core/conf/index',
                'is_menu' => 1,
                'sort' => 0,
                'pid' => 1,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-util',
                'des' => '常规管理',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '31' => [
                'name' => '系统配置',
                'rule' => 'plugin/core/conf/index',
                'is_menu' => 1,
                'sort' => 0,
                'pid' => 30,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-set-sm',
                'des' => '系统配置',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '32' => [
                'name' => '添加分组',
                'rule' => 'plugin/core/conf/addGroup',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 31,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-list',
                'des' => '添加分组',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '33' => [
                'name' => '编辑分组',
                'rule' => 'plugin/core/conf/editGroup',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 31,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-list',
                'des' => '编辑分组',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '34' => [
                'name' => '删除分组',
                'rule' => 'plugin/core/conf/delGroup',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 31,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-list',
                'des' => '删除分组',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '35' => [
                'name' => '添加配置项',
                'rule' => 'plugin/core/conf/addConfig',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 31,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-list',
                'des' => '添加配置项',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '36' => [
                'name' => '编辑配置项',
                'rule' => 'plugin/core/conf/editConfig',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 31,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-list',
                'des' => '编辑配置项',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '37' => [
                'name' => '删除配置项',
                'rule' => 'plugin/core/conf/delConfig',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 31,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-list',
                'des' => '删除配置项',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '38' => [
                'name' => '保存配置信息',
                'rule' => 'plugin/core/conf/set',
                'is_menu' => 2,
                'sort' => 0,
                'pid' => 31,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-list',
                'des' => '保存配置信息',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '39' => [
                'name' => '个人设置',
                'rule' => 'plugin/core/general/profile',
                'is_menu' => 1,
                'sort' => 0,
                'pid' => 30,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-username',
                'des' => '个人设置',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '40' => [
                'name' => '一键生成管理',
                'rule' => 'plugin/core/autocreate.curd/index',
                'is_menu' => 1,
                'sort' => 0,
                'pid' => 1,
                'is_show' => 1,
                'icon' => 'fa fa-bolt',
                'des' => '一键生成管理',
                'create_time' => time(),
                'update_time' => time(),
            ],
            '41' => [
                'name' => 'CURD',
                'rule' => 'plugin/core/autocreate.curd/index',
                'is_menu' => 1,
                'sort' => 0,
                'pid' => 40,
                'is_show' => 1,
                'icon' => 'layui-icon layui-icon-rate-solid',
                'des' => 'CURD',
                'create_time' => time(),
                'update_time' => time(),
            ]
        ];

        $table->setData($data)->create();
    }
}