<?php

use think\migration\Migrator;

class AdminMenu extends Migrator
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function change()
    {
        $table = $this->table('admin_menu', [
            'engine'    => 'InnoDB',
            'comment'   => '后台菜单',
            'collation' => 'utf8mb4_general_ci',
        ]);

        if ($table->exists()) {
            $table->drop();
        }

        $table
            ->addColumn('name', 'string', ['length' => 100, 'default' => '', 'comment' => '名称'])
            ->addColumn('href', 'string', ['length' => 255, 'default' => '', 'comment' => '点击菜单，打开的url地址'])
            ->addColumn('open_type', 'string', ['length' => 255, 'default' => '_iframe', 'comment' => '打开方式,_iframe=iframe的地址和_blank=新窗口打开'])
            ->addColumn('rule', 'string', ['length' => 100, 'default' => '', 'comment' => '路由规则'])
            ->addColumn('is_menu', 'boolean', ['default' => 1, 'comment' => '是否为menu.2=不是,1=是'])
            ->addColumn('sort', 'integer', ['default' => 0, 'comment' => '排序，从大到小，倒叙排序'])
            ->addColumn('pid', 'integer', ['default' => 0, 'comment' => '上级ID'])
            ->addColumn('is_show', 'integer', ['default' => 1, 'comment' => '是否显示.2=隐藏,1=显示'])
            ->addColumn('icon', 'string', ['length' => 100, 'default' => '', 'comment' => '图标'])
            ->addColumn('des', 'text', ['comment' => '描述'])
            ->addColumn('create_time', 'datetime', ['null' => 1, 'comment' => '创建时间'])
            ->addColumn('update_time', 'datetime', ['null' => 1, 'comment' => '更新时间'])
            ->addColumn('delete_time', 'datetime', ['null' => 1, 'comment' => '删除时间']);

        $data = [
            '1'  => [
                'name'        => '控制台',
                'rule'        => '',
                'pid'         => 0,
                'des'         => '控制台',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '2'  => [
                'name'        => '控制面板',
                'href'        => '/admin/console.html',
                'open_type'   => '_iframe',
                'pid'         => 1,
                'icon'        => 'layui-icon layui-icon-console',
                'des'         => '控制面板',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '3'  => [
                'name'        => '权限管理',
                'pid'         => 1,
                'icon'        => 'layui-icon layui-icon-group',
                'des'         => '权限管理',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '4'  => [
                'name'        => '管理员管理',
                'href'        => '/admin/user/index.html',
                'open_type'   => '_iframe',
                'pid'         => 3,
                'des'         => '管理员管理',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '5'  => [
                'name'        => '查看和搜索列表',
                'rule'        => '/admin.user/index',
                'is_menu'     => 2,
                'pid'         => 4,
                'des'         => '查看和搜索列表',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '6'  => [
                'name'        => '查看单条数据详情',
                'rule'        => '/admin.user/info',
                'is_menu'     => 2,
                'pid'         => 4,
                'des'         => '查看单条数据详情',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '7'  => [
                'name'        => '添加',
                'rule'        => '/admin.user/add',
                'is_menu'     => 2,
                'pid'         => 4,
                'des'         => '添加',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '8'  => [
                'name'        => '编辑',
                'rule'        => '/admin.user/edit',
                'is_menu'     => 2,
                'pid'         => 4,
                'des'         => '编辑',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '9'  => [
                'name'        => '删除',
                'rule'        => '/admin.user/del',
                'is_menu'     => 2,
                'pid'         => 4,
                'des'         => '删除',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '10'  => [
                'name'        => '设置是否禁用',
                'rule'        => '/admin.user/setStatus',
                'is_menu'     => 2,
                'pid'         => 4,
                'des'         => '设置是否禁用',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '11' => [
                'name'        => '设置是否为超管',
                'rule'        => '/admin.user/setIsSuperManager',
                'is_menu'     => 2,
                'pid'         => 4,
                'des'         => '设置是否为超管',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '12' => [
                'name'        => '回收站',
                'rule'        => '/admin.user/recycle',
                'is_menu'     => 2,
                'pid'         => 4,
                'des'         => '回收站',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '13' => [
                'name'        => '还原',
                'rule'        => '/admin.user/restore',
                'is_menu'     => 2,
                'pid'         => 4,
                'des'         => '还原',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '14' => [
                'name'        => '真实删除',
                'rule'        => '/admin.user/trueDel',
                'is_menu'     => 2,
                'pid'         => 4,
                'des'         => '真实删除',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '15' => [
                'name'        => '角色管理',
                'href'        => '/admin/role/index.html',
                'open_type'   => '_iframe',
                'pid'         => 3,
                'des'         => '角色管理',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '16'  => [
                'name'        => '查看和搜索列表',
                'rule'        => '/admin.role/index',
                'is_menu'     => 2,
                'pid'         => 15,
                'des'         => '查看和搜索列表',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '17'  => [
                'name'        => '查看单条数据详情',
                'rule'        => '/admin.role/info',
                'is_menu'     => 2,
                'pid'         => 15,
                'des'         => '查看单条数据详情',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '18'  => [
                'name'        => '添加',
                'rule'        => '/admin.role/add',
                'is_menu'     => 2,
                'pid'         => 15,
                'des'         => '添加',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '19'  => [
                'name'        => '编辑',
                'rule'        => '/admin.role/edit',
                'is_menu'     => 2,
                'pid'         => 15,
                'des'         => '编辑',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '20'  => [
                'name'        => '删除',
                'rule'        => '/admin.role/del',
                'is_menu'     => 2,
                'pid'         => 15,
                'des'         => '删除',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '21' => [
                'name'        => '回收站',
                'rule'        => '/admin.role/recycle',
                'is_menu'     => 2,
                'pid'         => 15,
                'des'         => '回收站',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '22' => [
                'name'        => '还原',
                'rule'        => '/admin.role/restore',
                'is_menu'     => 2,
                'pid'         => 15,
                'des'         => '还原',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '23' => [
                'name'        => '真实删除',
                'rule'        => '/admin.role/trueDel',
                'is_menu'     => 2,
                'pid'         => 15,
                'des'         => '真实删除',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '24' => [
                'name'        => '菜单管理',
                'href'        => '/admin/menu/index.html',
                'open_type'   => '_iframe',
                'pid'         => 3,
                'des'         => '菜单管理',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '25'  => [
                'name'        => '查看和搜索列表',
                'rule'        => '/admin.menu/index',
                'is_menu'     => 2,
                'pid'         => 24,
                'des'         => '查看和搜索列表',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '26'  => [
                'name'        => '查看单条数据详情',
                'rule'        => '/admin.menu/info',
                'is_menu'     => 2,
                'pid'         => 24,
                'des'         => '查看单条数据详情',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '27'  => [
                'name'        => '添加',
                'rule'        => '/admin.menu/add',
                'is_menu'     => 2,
                'pid'         => 24,
                'des'         => '添加',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '28'  => [
                'name'        => '编辑',
                'rule'        => '/admin.menu/edit',
                'is_menu'     => 2,
                'pid'         => 24,
                'des'         => '编辑',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '29'  => [
                'name'        => '删除',
                'rule'        => '/admin.menu/del',
                'is_menu'     => 2,
                'pid'         => 24,
                'des'         => '删除',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '30'  => [
                'name'        => '设置是否为菜单',
                'rule'        => '/admin.menu/setIsMenu',
                'is_menu'     => 2,
                'pid'         => 24,
                'des'         => '设置是否为菜单',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '31'  => [
                'name'        => '设置是否显示',
                'rule'        => '/admin.menu/setIsShow',
                'is_menu'     => 2,
                'pid'         => 24,
                'des'         => '设置是否显示',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '32' => [
                'name'        => '回收站',
                'rule'        => '/admin.menu/recycle',
                'is_menu'     => 2,
                'pid'         => 24,
                'des'         => '回收站',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '33' => [
                'name'        => '还原',
                'rule'        => '/admin.menu/restore',
                'is_menu'     => 2,
                'pid'         => 24,
                'des'         => '还原',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '34' => [
                'name'        => '真实删除',
                'rule'        => '/admin.menu/trueDel',
                'is_menu'     => 2,
                'pid'         => 24,
                'des'         => '真实删除',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '35' => [
                'name'        => '系统配置',
                'pid'         => 1,
                'icon'        => 'layui-icon layui-icon-set-fill',
                'des'         => '系统配置',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '36' => [
                'name'        => '配置样例',
                'href'        => '/admin/conf/system/demo.html',
                'is_menu'     => 1,
                'pid'         => 35,
                'des'         => '配置样例',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '37' => [
                'name'        => '基础配置',
                'href'        => '/admin/conf/system/basic.html',
                'is_menu'     => 1,
                'pid'         => 35,
                'des'         => '基础配置',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '38' => [
                'name'        => '上传配置',
                'href'        => '/admin/conf/system/upload.html',
                'is_menu'     => 1,
                'pid'         => 35,
                'des'         => '上传配置',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '39' => [
                'name'        => '常规管理',
                'pid'         => 1,
                'icon'        => 'layui-icon layui-icon-set-sm',
                'des'         => '常规管理',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '40' => [
                'name'        => '附件相关',
                'pid'         => 39,
                'des'         => '附件相关',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '41' => [
                'name'        => '附件管理',
                'href'        => '/admin/files/index.html',
                'pid'         => 40,
                'des'         => '附件管理',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '42'  => [
                'name'        => '查看和搜索列表',
                'rule'        => '/admin.files/index',
                'is_menu'     => 2,
                'pid'         => 41,
                'des'         => '查看和搜索列表',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '43'  => [
                'name'        => '删除',
                'rule'        => '/admin.files/del',
                'is_menu'     => 2,
                'pid'         => 41,
                'des'         => '删除',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '44' => [
                'name'        => '回收站',
                'rule'        => '/admin.files/recycle',
                'is_menu'     => 2,
                'pid'         => 41,
                'des'         => '回收站',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '45' => [
                'name'        => '还原',
                'rule'        => '/admin.files/restore',
                'is_menu'     => 2,
                'pid'         => 41,
                'des'         => '还原',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '46' => [
                'name'        => '真实删除',
                'rule'        => '/admin.files/trueDel',
                'is_menu'     => 2,
                'pid'         => 41,
                'des'         => '真实删除',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '47' => [
                'name'        => '附件分类管理',
                'href'        => '/admin/files/category/index.html',
                'pid'         => 40,
                'des'         => '附件分类管理',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '48'  => [
                'name'        => '查看和搜索列表',
                'rule'        => '/admin.files.category/index',
                'is_menu'     => 2,
                'pid'         => 47,
                'des'         => '查看和搜索列表',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '49'  => [
                'name'        => '查看单条数据详情',
                'rule'        => '/admin.files.category/info',
                'is_menu'     => 2,
                'pid'         => 47,
                'des'         => '查看单条数据详情',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '50'  => [
                'name'        => '添加',
                'rule'        => '/admin.files.category/add',
                'is_menu'     => 2,
                'pid'         => 47,
                'des'         => '添加',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '51'  => [
                'name'        => '编辑',
                'rule'        => '/admin.files.category/edit',
                'is_menu'     => 2,
                'pid'         => 47,
                'des'         => '编辑',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '52'  => [
                'name'        => '删除',
                'rule'        => '/admin.files.category/del',
                'is_menu'     => 2,
                'pid'         => 47,
                'des'         => '删除',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '53' => [
                'name'        => '回收站',
                'rule'        => '/admin.files.category/recycle',
                'is_menu'     => 2,
                'pid'         => 47,
                'des'         => '回收站',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '54' => [
                'name'        => '还原',
                'rule'        => '/admin.files.category/restore',
                'is_menu'     => 2,
                'pid'         => 47,
                'des'         => '还原',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '55' => [
                'name'        => '真实删除',
                'rule'        => '/admin.files.category/trueDel',
                'is_menu'     => 2,
                'pid'         => 47,
                'des'         => '真实删除',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '56' => [
                'name'        => '地区管理',
                'href'        => '/admin/area/index.html',
                'pid'         => 39,
                'des'         => '地区管理',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '57'  => [
                'name'        => '查看和搜索列表',
                'rule'        => '/admin.area/index',
                'is_menu'     => 2,
                'pid'         => 56,
                'des'         => '查看和搜索列表',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '58'  => [
                'name'        => '查看单条数据详情',
                'rule'        => '/admin.area/info',
                'is_menu'     => 2,
                'pid'         => 56,
                'des'         => '查看单条数据详情',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '59'  => [
                'name'        => '添加',
                'rule'        => '/admin.area/add',
                'is_menu'     => 2,
                'pid'         => 56,
                'des'         => '添加',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '60'  => [
                'name'        => '编辑',
                'rule'        => '/admin.area/edit',
                'is_menu'     => 2,
                'pid'         => 56,
                'des'         => '编辑',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '61'  => [
                'name'        => '删除',
                'rule'        => '/admin.area/del',
                'is_menu'     => 2,
                'pid'         => 56,
                'des'         => '删除',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '62' => [
                'name'        => '回收站',
                'rule'        => '/admin.area/recycle',
                'is_menu'     => 2,
                'pid'         => 56,
                'des'         => '回收站',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '63' => [
                'name'        => '还原',
                'rule'        => '/admin.area/restore',
                'is_menu'     => 2,
                'pid'         => 56,
                'des'         => '还原',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '64' => [
                'name'        => '真实删除',
                'rule'        => '/admin.area/trueDel',
                'is_menu'     => 2,
                'pid'         => 56,
                'des'         => '真实删除',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '65' => [
                'name'        => '设置排序',
                'rule'        => '/admin.area/setSort',
                'is_menu'     => 2,
                'pid'         => 56,
                'des'         => '设置排序',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '66' => [
                'name'        => '日志相关',
                'href'        => '/admin/api/log/index.html',
                'pid'         => 39,
                'des'         => '日志相关',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '67' => [
                'name'        => '后台登录日志',
                'href'        => '/admin/login/log/index.html',
                'rule'        => '/admin.login.log/index',
                'pid'         => 66,
                'des'         => '后台登录日志',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '68' => [
                'name'        => '后台操作日志',
                'href'        => '/admin/action/log/index.html',
                'rule'        => '/admin.action.log/index',
                'pid'         => 66,
                'des'         => '后台操作日志',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '69' => [
                'name'        => 'Api请求日志',
                'href'        => '/admin/api/log/index.html',
                'rule'        => '/admin.api.log/index',
                'pid'         => 66,
                'des'         => 'Api请求日志',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '70' => [
                'name'        => '插件市场',
                'pid'         => 1,
                'href'        => '/admin/plugins/index.html',
                'icon'        => 'layui-icon layui-icon-component',
                'des'         => '插件市场',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '71' => [
                'name'        => '查看插件列表',
                'pid'         => 70,
                'rule'        => '/admin.plugins/index',
                'is_menu'     => 2,
                'des'         => '查看插件列表',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '72' => [
                'name'        => '查看插件分类列表',
                'pid'         => 70,
                'rule'        => '/admin.plugins/category',
                'is_menu'     => 2,
                'des'         => '查看插件分类列表',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '73' => [
                'name'        => '离线安装',
                'pid'         => 70,
                'rule'        => '/admin.plugins/offLineInstall',
                'is_menu'     => 2,
                'des'         => '离线安装',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '74' => [
                'name'        => '卸载',
                'pid'         => 70,
                'rule'        => '/admin.plugins/uninstall',
                'is_menu'     => 2,
                'des'         => '卸载',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
            '75' => [
                'name'        => '安装',
                'pid'         => 70,
                'rule'        => '/admin.plugins/install',
                'is_menu'     => 2,
                'des'         => '安装',
                'create_time' => date('Y-m-d H:i:s'),
                'update_time' => date('Y-m-d H:i:s'),
            ],
        ];

        $table->setData($data)->create();
    }
}