<?php
return [
    [
        'name'=>'AccessKeyID'
        ,'tip'=>'AccessKeyID'
        ,'key'=>'access_key_id'
        ,'type'=>'input'
        ,'content'=>''
    ],
    [
        'name'=>'AccessKeySecret'
        ,'tip'=>'AccessKeySecret'
        ,'key'=>'access_key_secret'
        ,'type'=>'input'
        ,'content'=>''
    ],
    [
        'name'=>'endpoint'
        ,'tip'=>'endpoint'
        ,'key'=>'endpoint'
        ,'type'=>'input'
        ,'content'=>''
    ],
    [
        'name'=>'bucket'
        ,'tip'=>'bucket'
        ,'key'=>'bucket'
        ,'type'=>'input'
        ,'content'=>''
    ],
    [
        'name'=>'空间域名'
        ,'tip'=>'空间域名'
        ,'key'=>'domain'
        ,'type'=>'input'
        ,'content'=>''
    ],
];
